apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: kedapoc-consumer
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      service: consumer
  template:
    metadata:
      labels:
        app: kedapoc-consumer
        service: consumer
    spec:
      imagePullSecrets:
      - name: acrsecret
      containers:
      - name: consumer
        image: acrchinhdo4.azurecr.io/kedapoc-consumer:latest
        #imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
